export {
  decodeSelection,
  DEFAULT_BULK_LIMITS,
  DEFAULT_STATE_DECODE_LIMITS,
  encodeSelection,
  toBulkSelection,
} from "./codec.js";
export type {
  BulkConversionResult,
  BulkLimits,
  BulkSelectionDraft,
  DecodeResult,
  EncodedSelectionDraft,
  IdDecoder,
  PayloadDecodeResult,
  PayloadError,
  PayloadErrorCode,
  SelectionDecodeOptions,
  StateDecodeLimits,
  TypedSelectionDecodeOptions,
} from "./codec.js";
export {
  applySelectionCommand,
  clearSelection,
  emptySelection,
  reconcileScope,
  refreshScopeToken,
  selectAllMatching,
  setIdSelected,
  setIdsSelected,
} from "./state.js";
export {
  createSelectionView,
  getPageSelection,
  isIdSelected,
  summarizeSelectionState,
} from "./view.js";
export type {
  AllMatchingScope,
  ClearSelectionCommand,
  PageSelection,
  ReconcileScopeInput,
  RefreshScopeTokenCommand,
  RefreshScopeTokenInput,
  RowId,
  ScopedRead,
  SelectionCommand,
  SelectionContext,
  SelectionState,
  SelectionStateSummary,
  SelectionView,
  SelectAllMatchingCommand,
  SetIdSelectedInput,
  SetIdsSelectedCommand,
  SetIdsSelectedInput,
  TransitionFailureReason,
  TransitionResult,
} from "./types.js";
